### ISSUE TITLE
Edit view : Display the list of questions

### ISSUE THREAD

**Issue by Vorn-Sreymao** [Vorn-Sreymao/2022-QUIZ-APP-G8#4]
TODO

Create a list of fake questions on Javascript

 the view to see the list of questions
 -    add question button 
 -    eidt/ remoe  question  button 
 -      the correct anwer

TO DECIDE

- What is the structure of your question ?

TO CHANGE
- HTML / CSS / JS

TO TEST

- the ist of fake question should be displayed on the view with the correct answer visible

**Comment by ronanpnc** [comment]
the good answer should not be editable in  the list of question

==> remove the radionoxes and display the right answer  as a not editable way (color or icon..
